### ISSUE TITLE
git submodule failed for ondc-mmi-service. ondc-mmi-service not properly configured in the sandbox

### ISSUE THREAD

**Issue by govindnetworks** [ONDC-Official/ondc-sdk#3]
lenovo@lenovo-ThinkPad-T470-W10DG:~/code/ondc/ondc-sandbox$ git submodule update --recursive
Cloning into '/home/lenovo/code/ondc/ondc-sandbox/ondc-mmi-service'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:dataorchestration/ondc-mmi-server.git' into submodule path '/home/lenovo/code/ondc/ondc-sandbox/ondc-mmi-service' failed
Failed to clone 'ondc-mmi-service'. Retry scheduled
Cloning into '/home/lenovo/code/ondc/ondc-sandbox/ondc-mmi-service'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:dataorchestration/ondc-mmi-server.git' into submodule path '/home/lenovo/code/ondc/ondc-sandbox/ondc-mmi-service' failed
Failed to clone 'ondc-mmi-service' a second time, aborting
lenovo@lenovo-ThinkPad-T470-W10DG:~/code/ondc/ondc-sandbox

**Comment by v-i-s-h** [comment]
+1
